seed: 1

mosaic:
  n_mosaics: 1
  mean_diameters: 12.0
  center_noise: 0.05
  diameter_noise: 0.05
  n_missing_list: 0
  overlap_factors: 1.0
  bounds: [0, 100, 0, 100]

features:
  n_dims: 2
  spread: 1.0
  std: 0.3
  aspect_ratio: 1.0
  rotation: null
  center_jitter: 0.0

output:
  filename: single.npz
